SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS user_info;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS level;
DROP TABLE IF EXISTS activity_type;
DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS participant;
DROP TABLE IF EXISTS equipment;

SET FOREIGN_KEY_CHECKS=1;